### ISSUE TITLE
Not working in Python 3.10rc2

### ISSUE THREAD

**Issue by Baneeishaque** [simion/pip-upgrader#43]

**Comment by matthewdeanmartin** [comment]
A namespace changed - https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections

Same for python 3.10
```
$ pip-upgrade --help
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\matth\.virtualenvs\demo_doc-j-5bRj6B\Scripts\pip-upgrade.exe\__main__.py", line 4, in <module>
  File "C:\Users\matth\.virtualenvs\demo_doc-j-5bRj6B\lib\site-packages\pip_upgrader\cli.py", line 31, in <module>
    from colorclass import Windows, Color
  File "C:\Users\matth\.virtualenvs\demo_doc-j-5bRj6B\lib\site-packages\colorclass\__init__.py", line 11, in <module>
    from colorclass.codes import list_tags  # noqa
  File "C:\Users\matth\.virtualenvs\demo_doc-j-5bRj6B\lib\site-packages\colorclass\codes.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Python310\lib\collections\__init__.py)
```
